// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "925aa783-1042-4779-a245-17177464a37d";

const char SSID[]               = "M34 de Marcos";    // Network SSID (name)
const char PASS[]               = "marcos123";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "zHyBmG8CLBeHmmpWJ@qQdFuRT";    // Secret device password


CloudLocation gpsLocation;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gpsLocation, READWRITE, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
